export type SeedProduct = {
  provider: string;
  title: string;
  category: 'Outerwear' | 'Tops' | 'Bottoms' | 'Shoes' | 'Accessories';
  price: number;
  currency: string;
  productUrl: string;
  imageUrl: string;
};

export function getSeedProducts(): SeedProduct[] {
  return [
    {
      provider: 'FashionHub',
      title: 'Classic Denim Jacket',
      category: 'Outerwear',
      price: 89.99,
      currency: 'CAD',
      productUrl: 'https://example.com/denim-jacket',
      imageUrl: 'https://picsum.photos/seed/denim/400/400',
    },
    {
      provider: 'UrbanFits',
      title: 'Wide Leg Trousers',
      category: 'Bottoms',
      price: 64.0,
      currency: 'CAD',
      productUrl: 'https://example.com/trousers',
      imageUrl: 'https://picsum.photos/seed/trousers/400/400',
    },
    {
      provider: 'StyleNow',
      title: 'White Sneaker Low',
      category: 'Shoes',
      price: 110.5,
      currency: 'CAD',
      productUrl: 'https://example.com/sneakers',
      imageUrl: 'https://picsum.photos/seed/sneaker/400/400',
    },
    {
      provider: 'UrbanFits',
      title: 'Red Streetwear Hoodie',
      category: 'Tops',
      price: 59.0,
      currency: 'CAD',
      productUrl: 'https://example.com/red-hoodie',
      imageUrl: 'https://picsum.photos/seed/redhoodie/400/400',
    },
    {
      provider: 'UrbanFits',
      title: 'Black Oversized Tee',
      category: 'Tops',
      price: 35.0,
      currency: 'CAD',
      productUrl: 'https://example.com/oversized-tee',
      imageUrl: 'https://picsum.photos/seed/oversizedtee/400/400',
    },
    {
      provider: 'FashionHub',
      title: 'Beige Minimal Trench Coat',
      category: 'Outerwear',
      price: 129.0,
      currency: 'CAD',
      productUrl: 'https://example.com/minimal-trench',
      imageUrl: 'https://picsum.photos/seed/minimaltrench/400/400',
    },
    {
      provider: 'StyleNow',
      title: 'Blue Classic Oxford Shirt',
      category: 'Tops',
      price: 79.0,
      currency: 'CAD',
      productUrl: 'https://example.com/oxford-shirt',
      imageUrl: 'https://picsum.photos/seed/oxford/400/400',
    },
    {
      provider: 'StyleNow',
      title: 'Green Utility Cargo Pants',
      category: 'Bottoms',
      price: 84.0,
      currency: 'CAD',
      productUrl: 'https://example.com/cargo-pants',
      imageUrl: 'https://picsum.photos/seed/cargo/400/400',
    },
    {
      provider: 'LuxeLane',
      title: 'White Slim Fit Blazer',
      category: 'Outerwear',
      price: 189.0,
      currency: 'CAD',
      productUrl: 'https://example.com/slim-blazer',
      imageUrl: 'https://picsum.photos/seed/slimblazer/400/400',
    },
    {
      provider: 'LuxeLane',
      title: 'Navy Tailored Chinos',
      category: 'Bottoms',
      price: 119.0,
      currency: 'CAD',
      productUrl: 'https://example.com/tailored-chinos',
      imageUrl: 'https://picsum.photos/seed/chinos/400/400',
    },
    {
      provider: 'BudgetChic',
      title: 'Yellow Cropped Cardigan',
      category: 'Tops',
      price: 42.0,
      currency: 'CAD',
      productUrl: 'https://example.com/cropped-cardigan',
      imageUrl: 'https://picsum.photos/seed/cardigan/400/400',
    },
    {
      provider: 'BudgetChic',
      title: 'Pink Pleated Skirt',
      category: 'Bottoms',
      price: 49.0,
      currency: 'CAD',
      productUrl: 'https://example.com/pleated-skirt',
      imageUrl: 'https://picsum.photos/seed/pleatedskirt/400/400',
    },
    {
      provider: 'SneakPeak',
      title: 'Black Runner Pro',
      category: 'Shoes',
      price: 95.0,
      currency: 'CAD',
      productUrl: 'https://example.com/runner-pro',
      imageUrl: 'https://picsum.photos/seed/runnerpro/400/400',
    },
    {
      provider: 'SneakPeak',
      title: 'Red High-Top Street Sneaker',
      category: 'Shoes',
      price: 125.0,
      currency: 'CAD',
      productUrl: 'https://example.com/hightop-sneaker',
      imageUrl: 'https://picsum.photos/seed/hightop/400/400',
    },
    {
      provider: 'ClassicCo',
      title: 'Brown Leather Loafer',
      category: 'Shoes',
      price: 138.0,
      currency: 'CAD',
      productUrl: 'https://example.com/leather-loafer',
      imageUrl: 'https://picsum.photos/seed/loafer/400/400',
    },
    {
      provider: 'ClassicCo',
      title: 'Grey Wool Scarf',
      category: 'Accessories',
      price: 39.0,
      currency: 'CAD',
      productUrl: 'https://example.com/wool-scarf',
      imageUrl: 'https://picsum.photos/seed/woolscarf/400/400',
    },
    {
      provider: 'MinimalMode',
      title: 'White Capsule Tee',
      category: 'Tops',
      price: 29.0,
      currency: 'CAD',
      productUrl: 'https://example.com/capsule-tee',
      imageUrl: 'https://picsum.photos/seed/capsuletee/400/400',
    },
    {
      provider: 'MinimalMode',
      title: 'Black Straight Jeans',
      category: 'Bottoms',
      price: 69.0,
      currency: 'CAD',
      productUrl: 'https://example.com/straight-jeans',
      imageUrl: 'https://picsum.photos/seed/straightjeans/400/400',
    },
    {
      provider: 'AthletiStyle',
      title: 'Blue Performance Jogger',
      category: 'Bottoms',
      price: 74.0,
      currency: 'CAD',
      productUrl: 'https://example.com/performance-jogger',
      imageUrl: 'https://picsum.photos/seed/jogger/400/400',
    },
    {
      provider: 'AthletiStyle',
      title: 'Green Training Jacket',
      category: 'Outerwear',
      price: 88.0,
      currency: 'CAD',
      productUrl: 'https://example.com/training-jacket',
      imageUrl: 'https://picsum.photos/seed/trainingjacket/400/400',
    },
    {
      provider: 'TrendDrop',
      title: 'Purple Statement Bomber',
      category: 'Outerwear',
      price: 149.0,
      currency: 'CAD',
      productUrl: 'https://example.com/statement-bomber',
      imageUrl: 'https://picsum.photos/seed/statementbomber/400/400',
    },
    {
      provider: 'TrendDrop',
      title: 'Orange Retro Windbreaker',
      category: 'Outerwear',
      price: 99.0,
      currency: 'CAD',
      productUrl: 'https://example.com/retro-windbreaker',
      imageUrl: 'https://picsum.photos/seed/windbreaker/400/400',
    },
    {
      provider: 'UrbanFits',
      title: 'Beige Bucket Hat',
      category: 'Accessories',
      price: 24.0,
      currency: 'CAD',
      productUrl: 'https://example.com/bucket-hat',
      imageUrl: 'https://picsum.photos/seed/buckethat/400/400',
    },
  ];
}
